[project]
name = "news-summariser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.120.1",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
